"""initial migration

Revision ID: b409467ecd8d
Revises: 
Create Date: 2025-10-04 12:24:42.853403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b409467ecd8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('pitch_type', sa.String(), nullable=True),
    sa.Column('bounce_rating', sa.Float(), nullable=True),
    sa.Column('grass_coverage', sa.Float(), nullable=True),
    sa.Column('cracks_present', sa.Boolean(), nullable=True),
    sa.Column('avg_first_innings_score', sa.Float(), nullable=True),
    sa.Column('favor_spin', sa.Boolean(), nullable=True),
    sa.Column('favor_pace', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_stadiums_id'), 'stadiums', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('format', sa.Enum('TEST', 'ODI', 'T20', 'T10', name='matchformat'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('head_to_head_team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('TEST', 'ODI', 'T20', 'T10', name='matchformat'), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('team_a_wins', sa.Integer(), nullable=True),
    sa.Column('team_b_wins', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('no_results', sa.Integer(), nullable=True),
    sa.Column('avg_score_team_a', sa.Float(), nullable=True),
    sa.Column('avg_score_team_b', sa.Float(), nullable=True),
    sa.Column('net_run_rate_a_vs_b', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_a_id', 'team_b_id', 'format', name='uq_team_h2h')
    )
    op.create_index('ix_h2h_team_pair', 'head_to_head_team_stats', ['team_a_id', 'team_b_id', 'format'], unique=False)
    op.create_index(op.f('ix_head_to_head_team_stats_team_a_id'), 'head_to_head_team_stats', ['team_a_id'], unique=False)
    op.create_index(op.f('ix_head_to_head_team_stats_team_b_id'), 'head_to_head_team_stats', ['team_b_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('format', sa.Enum('TEST', 'ODI', 'T20', 'T10', name='matchformat'), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('toss_winner_id', sa.Integer(), nullable=True),
    sa.Column('toss_decision', sa.Enum('BAT', 'FIELD', name='tossdecision'), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.ForeignKeyConstraint(['toss_winner_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_tournament_id'), 'matches', ['tournament_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('batting_style', sa.String(), nullable=True),
    sa.Column('bowling_style', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('BATSMAN', 'BOWLER', 'WICKET_KEEPER', 'ALL_ROUNDER', name='playerrole'), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_team_id'), 'players', ['team_id'], unique=False)
    op.create_table('team_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('no_results', sa.Integer(), nullable=True),
    sa.Column('total_runs_scored', sa.Integer(), nullable=True),
    sa.Column('total_runs_conceded', sa.Integer(), nullable=True),
    sa.Column('wickets_taken', sa.Integer(), nullable=True),
    sa.Column('wickets_lost', sa.Integer(), nullable=True),
    sa.Column('net_run_rate', sa.Float(), nullable=True),
    sa.Column('win_percentage', sa.Float(), nullable=True),
    sa.Column('recent_form', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'tournament_id', name='uq_team_tournament_stats')
    )
    op.create_index(op.f('ix_team_stats_team_id'), 'team_stats', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_stats_tournament_id'), 'team_stats', ['tournament_id'], unique=False)
    op.create_table('innings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('batting_team_id', sa.Integer(), nullable=True),
    sa.Column('bowling_team_id', sa.Integer(), nullable=True),
    sa.Column('innings_number', sa.Integer(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('total_wickets', sa.Integer(), nullable=True),
    sa.Column('overs_completed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['batting_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['bowling_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_innings_match_id'), 'innings', ['match_id'], unique=False)
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('balls_faced', sa.Integer(), nullable=True),
    sa.Column('wickets_taken', sa.Integer(), nullable=True),
    sa.Column('overs_bowled', sa.Float(), nullable=True),
    sa.Column('economy_rate', sa.Float(), nullable=True),
    sa.Column('strike_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'match_id', name='uq_player_match_stats')
    )
    op.create_index(op.f('ix_player_stats_match_id'), 'player_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_table('player_vs_bowler_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batsman_id', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('TEST', 'ODI', 'T20', 'T10', name='matchformat'), nullable=False),
    sa.Column('balls_faced', sa.Integer(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('dismissals', sa.Integer(), nullable=True),
    sa.Column('strike_rate', sa.Float(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('dot_ball_percentage', sa.Float(), nullable=True),
    sa.Column('boundary_percentage', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batsman_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batsman_id', 'bowler_id', 'format', name='uq_player_bowler_stats')
    )
    op.create_index('ix_batsman_bowler_pair', 'player_vs_bowler_stats', ['batsman_id', 'bowler_id', 'format'], unique=False)
    op.create_index(op.f('ix_player_vs_bowler_stats_batsman_id'), 'player_vs_bowler_stats', ['batsman_id'], unique=False)
    op.create_index(op.f('ix_player_vs_bowler_stats_bowler_id'), 'player_vs_bowler_stats', ['bowler_id'], unique=False)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed_kph', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_match_id'), 'weather_data', ['match_id'], unique=False)
    op.create_table('overs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('innings_id', sa.Integer(), nullable=True),
    sa.Column('over_number', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overs_innings_id'), 'overs', ['innings_id'], unique=False)
    op.create_table('balls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('over_id', sa.Integer(), nullable=True),
    sa.Column('ball_number', sa.Integer(), nullable=False),
    sa.Column('batsman_id', sa.Integer(), nullable=True),
    sa.Column('non_striker_id', sa.Integer(), nullable=True),
    sa.Column('bowler_id', sa.Integer(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('extras_type', sa.String(), nullable=True),
    sa.Column('extras_runs', sa.Integer(), nullable=True),
    sa.Column('wicket_type', sa.Enum('BOWLED', 'CAUGHT', 'LBW', 'RUN_OUT', 'STUMPED', 'HIT_WICKET', 'RETIRED', 'OTHER', name='wickettype'), nullable=True),
    sa.Column('player_out_id', sa.Integer(), nullable=True),
    sa.Column('is_boundary', sa.Boolean(), nullable=True),
    sa.Column('is_six', sa.Boolean(), nullable=True),
    sa.Column('is_powerplay', sa.Boolean(), nullable=True),
    sa.Column('phase', sa.Enum('POWER_PLAY', 'MIDDLE', 'DEATH', name='ballphase'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batsman_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['non_striker_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['over_id'], ['overs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_out_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balls_over_id'), 'balls', ['over_id'], unique=False)
    op.create_table('situational_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('innings_id', sa.Integer(), nullable=True),
    sa.Column('over_id', sa.Integer(), nullable=True),
    sa.Column('momentum_index', sa.Float(), nullable=True),
    sa.Column('pressure_overs_index', sa.Float(), nullable=True),
    sa.Column('batting_form_index', sa.Float(), nullable=True),
    sa.Column('bowling_form_index', sa.Float(), nullable=True),
    sa.Column('pitch_adjusted_score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['over_id'], ['overs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_situational_metrics_innings_id'), 'situational_metrics', ['innings_id'], unique=False)
    op.create_index(op.f('ix_situational_metrics_match_id'), 'situational_metrics', ['match_id'], unique=False)
    op.create_index(op.f('ix_situational_metrics_over_id'), 'situational_metrics', ['over_id'], unique=False)
    op.create_index(op.f('ix_situational_metrics_team_id'), 'situational_metrics', ['team_id'], unique=False)
    op.create_table('probability_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('innings_id', sa.Integer(), nullable=True),
    sa.Column('ball_id', sa.Integer(), nullable=True),
    sa.Column('draw_prob', sa.Float(), nullable=True),
    sa.Column('no_result_prob', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('runs_remaining', sa.Integer(), nullable=True),
    sa.Column('balls_remaining', sa.Integer(), nullable=True),
    sa.Column('wickets_remaining', sa.Integer(), nullable=True),
    sa.Column('win_prob_team1', sa.Float(), nullable=True),
    sa.Column('win_prob_team2', sa.Float(), nullable=True),
    sa.Column('expected_score', sa.Float(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('training_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ball_id'], ['balls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prob_state_match_innings_ball', 'probability_state', ['match_id', 'innings_id', 'ball_id'], unique=False)
    op.create_index(op.f('ix_probability_state_ball_id'), 'probability_state', ['ball_id'], unique=False)
    op.create_index(op.f('ix_probability_state_innings_id'), 'probability_state', ['innings_id'], unique=False)
    op.create_index(op.f('ix_probability_state_match_id'), 'probability_state', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_probability_state_match_id'), table_name='probability_state')
    op.drop_index(op.f('ix_probability_state_innings_id'), table_name='probability_state')
    op.drop_index(op.f('ix_probability_state_ball_id'), table_name='probability_state')
    op.drop_index('ix_prob_state_match_innings_ball', table_name='probability_state')
    op.drop_table('probability_state')
    op.drop_index(op.f('ix_situational_metrics_team_id'), table_name='situational_metrics')
    op.drop_index(op.f('ix_situational_metrics_over_id'), table_name='situational_metrics')
    op.drop_index(op.f('ix_situational_metrics_match_id'), table_name='situational_metrics')
    op.drop_index(op.f('ix_situational_metrics_innings_id'), table_name='situational_metrics')
    op.drop_table('situational_metrics')
    op.drop_index(op.f('ix_balls_over_id'), table_name='balls')
    op.drop_table('balls')
    op.drop_index(op.f('ix_overs_innings_id'), table_name='overs')
    op.drop_table('overs')
    op.drop_index(op.f('ix_weather_data_match_id'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_player_vs_bowler_stats_bowler_id'), table_name='player_vs_bowler_stats')
    op.drop_index(op.f('ix_player_vs_bowler_stats_batsman_id'), table_name='player_vs_bowler_stats')
    op.drop_index('ix_batsman_bowler_pair', table_name='player_vs_bowler_stats')
    op.drop_table('player_vs_bowler_stats')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_match_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_innings_match_id'), table_name='innings')
    op.drop_table('innings')
    op.drop_index(op.f('ix_team_stats_tournament_id'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_team_id'), table_name='team_stats')
    op.drop_table('team_stats')
    op.drop_index(op.f('ix_players_team_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_tournament_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_head_to_head_team_stats_team_b_id'), table_name='head_to_head_team_stats')
    op.drop_index(op.f('ix_head_to_head_team_stats_team_a_id'), table_name='head_to_head_team_stats')
    op.drop_index('ix_h2h_team_pair', table_name='head_to_head_team_stats')
    op.drop_table('head_to_head_team_stats')
    op.drop_table('tournaments')
    op.drop_table('teams')
    op.drop_index(op.f('ix_stadiums_id'), table_name='stadiums')
    op.drop_table('stadiums')
    # ### end Alembic commands ###
